<?php

// Generate Google Fonts PHP Array
// Generated from https://github.com/EmranAhmed/google-fonts-php

return array(

	'barlow' => array(
		'id'       => 'barlow',
		'name'     => "Barlow",
		'label'    => "Barlow, sans-serif",
		'family'   => "Barlow, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
			'100i'  =>  'Thin 100 Italic',
			'200i'  =>  'Extra light 200 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
			'800i'  =>  'Extra bold 800 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'cormorant-garamond' => array(
		'id'       => 'cormorant-garamond',
		'name'     => "Cormorant Garamond",
		'label'    => "'Cormorant Garamond', serif",
		'family'   => "Cormorant Garamond, serif",
		'category' => "serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
		),
	),

	'fira-sans' => array(
		'id'       => 'fira-sans',
		'name'     => "Fira Sans",
		'label'    => "'Fira Sans', sans-serif",
		'family'   => "Fira Sans, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'greek'  => 'Greek',
			'greek-ext'  => 'Greek Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
			'100i'  =>  'Thin 100 Italic',
			'200i'  =>  'Extra light 200 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
			'800i'  =>  'Extra bold 800 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'fira-sans-condensed' => array(
		'id'       => 'fira-sans-condensed',
		'name'     => "Fira Sans Condensed",
		'label'    => "'Fira Sans Condensed', sans-serif",
		'family'   => "Fira Sans Condensed, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'greek'  => 'Greek',
			'greek-ext'  => 'Greek Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
			'100i'  =>  'Thin 100 Italic',
			'200i'  =>  'Extra light 200 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
			'800i'  =>  'Extra bold 800 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'inter' => array(
		'id'       => 'inter',
		'name'     => "Inter",
		'label'    => "Inter, sans-serif",
		'family'   => "Inter, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'greek'  => 'Greek',
			'greek-ext'  => 'Greek Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
		),
	),

	'lato' => array(
		'id'       => 'lato',
		'name'     => "Lato",
		'label'    => "Lato, sans-serif",
		'family'   => "Lato, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'700'  =>  'Bold 700',
			'900'  =>  'Black 900',
			'100i'  =>  'Thin 100 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'700i'  =>  'Bold 700 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'merriweather' => array(
		'id'       => 'merriweather',
		'name'     => "Merriweather",
		'label'    => "Merriweather, serif",
		'family'   => "Merriweather, serif",
		'category' => "serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'700'  =>  'Bold 700',
			'900'  =>  'Black 900',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'700i'  =>  'Bold 700 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'montserrat' => array(
		'id'       => 'montserrat',
		'name'     => "Montserrat",
		'label'    => "Montserrat, sans-serif",
		'family'   => "Montserrat, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
			'100i'  =>  'Thin 100 Italic',
			'200i'  =>  'Extra light 200 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
			'800i'  =>  'Extra bold 800 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'noto-sans' => array(
		'id'       => 'noto-sans',
		'name'     => "Noto Sans",
		'label'    => "'Noto Sans', sans-serif",
		'family'   => "Noto Sans, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'devanagari'  => 'Devanagari',
			'greek'  => 'Greek',
			'greek-ext'  => 'Greek Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'400'  =>  'Regular 400',
			'700'  =>  'Bold 700',
			'400i'  =>  'Regular 400 Italic',
			'700i'  =>  'Bold 700 Italic',
		),
	),

	'noto-sans-mono' => array(
		'id'       => 'noto-sans-mono',
		'name'     => "Noto Sans Mono",
		'label'    => "'Noto Sans Mono', monospace",
		'family'   => "Noto Sans Mono, monospace",
		'category' => "monospace",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'greek'  => 'Greek',
			'greek-ext'  => 'Greek Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
		),
	),

	'nunito-sans' => array(
		'id'       => 'nunito-sans',
		'name'     => "Nunito Sans",
		'label'    => "'Nunito Sans', sans-serif",
		'family'   => "Nunito Sans, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
			'200i'  =>  'Extra light 200 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
			'800i'  =>  'Extra bold 800 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'noto-serif' => array(
		'id'       => 'noto-serif',
		'name'     => "Noto Serif",
		'label'    => "'Noto Serif', serif",
		'family'   => "Noto Serif, serif",
		'category' => "serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'greek'  => 'Greek',
			'greek-ext'  => 'Greek Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'400'  =>  'Regular 400',
			'700'  =>  'Bold 700',
			'400i'  =>  'Regular 400 Italic',
			'700i'  =>  'Bold 700 Italic',
		),
	),

	'open-sans' => array(
		'id'       => 'open-sans',
		'name'     => "Open Sans",
		'label'    => "'Open Sans', sans-serif",
		'family'   => "Open Sans, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'greek'  => 'Greek',
			'greek-ext'  => 'Greek Extended',
			'hebrew'  => 'Hebrew',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
			'800i'  =>  'Extra bold 800 Italic',
		),
	),

	'oswald' => array(
		'id'       => 'oswald',
		'name'     => "Oswald",
		'label'    => "Oswald, sans-serif",
		'family'   => "Oswald, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
		),
	),

	'poppins' => array(
		'id'       => 'poppins',
		'name'     => "Poppins",
		'label'    => "Poppins, sans-serif",
		'family'   => "Poppins, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'devanagari'  => 'Devanagari',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
			'100i'  =>  'Thin 100 Italic',
			'200i'  =>  'Extra light 200 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
			'800i'  =>  'Extra bold 800 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'playfair-display' => array(
		'id'       => 'playfair-display',
		'name'     => "Playfair Display",
		'label'    => "'Playfair Display', serif",
		'family'   => "Playfair Display, serif",
		'category' => "serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
			'800i'  =>  'Extra bold 800 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'roboto' => array(
		'id'       => 'roboto',
		'name'     => "Roboto",
		'label'    => "Roboto, sans-serif",
		'family'   => "Roboto, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'greek'  => 'Greek',
			'greek-ext'  => 'Greek Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'700'  =>  'Bold 700',
			'900'  =>  'Black 900',
			'100i'  =>  'Thin 100 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'700i'  =>  'Bold 700 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'roboto-slab' => array(
		'id'       => 'roboto-slab',
		'name'     => "Roboto Slab",
		'label'    => "'Roboto Slab', serif",
		'family'   => "Roboto Slab, serif",
		'category' => "serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'greek'  => 'Greek',
			'greek-ext'  => 'Greek Extended',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'100'  =>  'Thin 100',
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'800'  =>  'Extra bold 800',
			'900'  =>  'Black 900',
		),
	),

	'source-serif-pro' => array(
		'id'       => 'source-serif-pro',
		'name'     => "Source Serif Pro",
		'label'    => "'Source Serif Pro', serif",
		'family'   => "Source Serif Pro, serif",
		'category' => "serif",
		'subsets'  => array(
			'cyrillic'  => 'Cyrillic',
			'cyrillic-ext'  => 'Cyrillic Extended',
			'greek'  => 'Greek',
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
			'vietnamese'  => 'Vietnamese',
		),
		'variants'  => array(
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'900'  =>  'Black 900',
			'200i'  =>  'Extra light 200 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
			'900i'  =>  'Black 900 Italic',
		),
	),

	'titillium-web' => array(
		'id'       => 'titillium-web',
		'name'     => "Titillium Web",
		'label'    => "'Titillium Web', sans-serif",
		'family'   => "Titillium Web, sans-serif",
		'category' => "sans-serif",
		'subsets'  => array(
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
		),
		'variants'  => array(
			'200'  =>  'Extra light 200',
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'900'  =>  'Black 900',
			'200i'  =>  'Extra light 200 Italic',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
		),
	),

	'zilla-slab' => array(
		'id'       => 'zilla-slab',
		'name'     => "Zilla Slab",
		'label'    => "'Zilla Slab', serif",
		'family'   => "Zilla Slab, serif",
		'category' => "serif",
		'subsets'  => array(
			'latin'  => 'Latin',
			'latin-ext'  => 'Latin Extended',
		),
		'variants'  => array(
			'300'  =>  'Light 300',
			'400'  =>  'Regular 400',
			'500'  =>  'Medium 500',
			'600'  =>  'Semi bold 600',
			'700'  =>  'Bold 700',
			'300i'  =>  'Light 300 Italic',
			'400i'  =>  'Regular 400 Italic',
			'500i'  =>  'Medium 400 Italic',
			'600i'  =>  'Semi bold 600 Italic',
			'700i'  =>  'Bold 700 Italic',
		),
	),

);